M48
; DRILL file {KiCad 7.0.10} date Thursday, January 18, 2024 at 11:30:59 AM
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-01-18T11:30:59-08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.10
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T1C0.0157
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.0394
%
G90
G05
T1
X6.4Y-3.7
X6.4Y-4.0
X6.6Y-4.5
X7.0Y-4.1
T2
X6.6286Y-3.8
X6.7271Y-3.8
M30
